meta:
  id: bfs
  title: BFS Traversal
  tags: [graph, algorithm, bfs]
  level: beginner
  order: 2

views:
  - { id: v3d, type: 3d }
  - { id: vgraph, type: graph }
  - { id: vplot, type: plot }
  - { id: vinspector, type: inspector }

entities:
  - { id: A, type: node, label: A, props: { value: 1 } }
  - { id: B, type: node, label: B, props: { value: 2 } }
  - { id: C, type: node, label: C, props: { value: 3 } }
  - { id: D, type: node, label: D, props: { value: 4 } }
  - { id: E, type: node, label: E, props: { value: 5 } }
  - { id: F, type: node, label: F, props: { value: 6 } }
  - id: visited-badge
    type: badge
    position: [-2.8, 1.6, 0]
    props:
      value: "visited:0"
      color: "#2563eb"
  - id: frontier-badge
    type: badge
    position: [-2.8, 1.2, 0]
    props:
      value: "frontier:1"
      color: "#ea580c"
  - id: active-badge
    type: badge
    position: [-2.8, 0.8, 0]
    props:
      value: "active:-"
      color: "#16a34a"

relations:
  - { id: r1, type: link, source: A, target: B }
  - { id: r2, type: link, source: A, target: C }
  - { id: r3, type: link, source: B, target: D }
  - { id: r4, type: link, source: B, target: E }
  - { id: r5, type: link, source: C, target: F }

process:
  id: bfs
  type: bfs
  config:
    startNodeId: A
    targetNodeId: F

ui:
  sliders:
    - id: bfs_level_gap
      label: Level Gap
      min: 0.7
      max: 2.4
      step: 0.05
      value: 1.3
    - id: bfs_branch_spread
      label: Branch Spread
      min: 0.8
      max: 3.4
      step: 0.05
      value: 1.8
  bindings:
    - target: A
      property: x
      value: 0
    - target: A
      property: z
      value: 0

    - target: B
      property: x
      expr: -0.55 * state.bfs_branch_spread
    - target: B
      property: z
      expr: -1 * state.bfs_level_gap

    - target: C
      property: x
      expr: 0.55 * state.bfs_branch_spread
    - target: C
      property: z
      expr: -1 * state.bfs_level_gap

    - target: D
      property: x
      expr: -1.1 * state.bfs_branch_spread
    - target: D
      property: z
      expr: -2 * state.bfs_level_gap

    - target: E
      property: x
      value: 0
    - target: E
      property: z
      expr: -2 * state.bfs_level_gap

    - target: F
      property: x
      expr: 1.1 * state.bfs_branch_spread
    - target: F
      property: z
      expr: -2 * state.bfs_level_gap

timeline:
  duration: 7.2
  loop: false
  speed: 1
  markers:
    - time: 0
      label: Start
      description: Begin at node A and initialize the frontier queue.
    - time: 2.4
      label: Level 2
      description: Second-layer nodes are now being expanded from the queue.
    - time: 6
      label: Complete
      description: Target node F is visited and traversal is complete.
  tracks:
    - id: steps
      type: step
      processId: bfs
      steps:
        - { index: 0, time: 0, label: A, payload: { nodeId: A } }
        - { index: 1, time: 1.2, label: B, payload: { nodeId: B } }
        - { index: 2, time: 2.4, label: C, payload: { nodeId: C } }
        - { index: 3, time: 3.6, label: D, payload: { nodeId: D } }
        - { index: 4, time: 4.8, label: E, payload: { nodeId: E } }
        - { index: 5, time: 6.0, label: F, payload: { nodeId: F } }
    - id: bfs-state
      type: state
      processId: bfs
      states:
        - { time: 0.0, state: idle }
        - { time: 6.0, state: completed }
    - id: bfs-events
      type: event
      processId: bfs
      events:
        - { time: 0, action: visit, params: { nodeId: A, step: 0 } }
        - { time: 1.2, action: visit, params: { nodeId: B, step: 1 } }
        - { time: 2.4, action: visit, params: { nodeId: C, step: 2 } }
        - { time: 3.6, action: visit, params: { nodeId: D, step: 3 } }
        - { time: 4.8, action: visit, params: { nodeId: E, step: 4 } }
        - { time: 6.0, action: visit, params: { nodeId: F, step: 5 } }
    - id: visited-metric
      type: property
      target: visited-badge
      property: value
      keyframes:
        - { time: 0.0, value: "visited:1" }
        - { time: 1.2, value: "visited:2" }
        - { time: 2.4, value: "visited:3" }
        - { time: 3.6, value: "visited:4" }
        - { time: 4.8, value: "visited:5" }
        - { time: 6.0, value: "visited:6" }
    - id: frontier-metric
      type: property
      target: frontier-badge
      property: value
      keyframes:
        - { time: 0.0, value: "frontier:2" }
        - { time: 1.2, value: "frontier:3" }
        - { time: 2.4, value: "frontier:3" }
        - { time: 3.6, value: "frontier:2" }
        - { time: 4.8, value: "frontier:1" }
        - { time: 6.0, value: "frontier:0" }
    - id: active-node
      type: property
      target: active-badge
      property: value
      keyframes:
        - { time: 0.0, value: "active:A" }
        - { time: 1.2, value: "active:B" }
        - { time: 2.4, value: "active:C" }
        - { time: 3.6, value: "active:D" }
        - { time: 4.8, value: "active:E" }
        - { time: 6.0, value: "active:F" }
