meta:
  id: gradient-descent
  title: Gradient Descent
  tags: [numeric, optimization]
  level: intermediate
  order: 3

views:
  - { id: v3d, type: 3d }
  - { id: vplot, type: plot }
  - { id: vinspector, type: inspector }

entities:
  - id: loss-field
    type: surface_field
    position: [0, -0.01, 0]
    props:
      mode: both
      size: [6, 6]
      resolution: 80
      opacity: 0.65
      surfaceOpacity: 0.28
      surfaceWireframe: true
      heightScale: 1.35
      heightMode: normalized
      surfaceYOffset: 0.06
      isoCount: 7
      isoColor: "#e2e8f0"
      coefficients:
        a: 1.0
        b: 1.0
        c: 0.2

  - id: grad-field
    type: vector_field
    position: [0, 0.03, 0]
    props:
      size: [6, 6]
      resolution: 10
      mode: both
      opacity: 0.96
      arrowScale: 0.26
      streamlineSeeds: 8
      streamlineSteps: 40
      coefficients:
        vxX: -2.0
        vxZ: -0.2
        vzX: -0.2
        vzZ: -2.0

  - id: point
    type: marker
    anchor: center
    color: "#00d084"
    label: theta

  - id: trajectory
    type: step_sequence
    props:
      color: "#22d3ee"
      activeColor: "#f97316"
      currentStep: 0
      steps:
        - { x: 2.5, y: 0.0, z: -1.8, label: s0 }
        - { x: 1.572, y: 0.0, z: -1.18, label: s1 }
        - { x: 0.9904, y: 0.0, z: -0.7708, label: s2 }
        - { x: 0.6251, y: 0.0, z: -0.5021, label: s3 }
        - { x: 0.3951, y: 0.0, z: -0.3263, label: s4 }

  - id: loss-probe
    type: sample_probe
    props:
      fieldId: loss-field
      label: f(theta)
      followMouse: true
      color: "#f8fafc"
      height: 1.15
  - id: loss-badge
    type: badge
    position: [2.8, 1.25, 0]
    props:
      value: "loss:8.59"
      color: "#334155"

process:
  id: gd
  type: gradient_descent
  config:
    pointEntityId: point
    startPoint: [2.5, -1.8]
    learningRate: 0.2
    maxIterations: 5
    epsilon: 0.001
    coefficients:
      a: 1.0
      b: 1.0
      c: 0.2

ui:
  sliders:
    - id: surface_resolution
      label: Surface Resolution
      min: 24
      max: 120
      step: 2
      value: 80
    - id: contour_count
      label: Contour Count
      min: 3
      max: 14
      step: 1
      value: 7
    - id: vector_gain
      label: Gradient Arrow Gain
      min: 0.08
      max: 0.55
      step: 0.01
      value: 0.26
    - id: streamline_density
      label: Streamline Seeds
      min: 4
      max: 18
      step: 1
      value: 8
  bindings:
    - target: loss-field
      property: resolution
      expr: Math.round(state.surface_resolution)
    - target: loss-field
      property: isoCount
      expr: Math.round(state.contour_count)
    - target: grad-field
      property: arrowScale
      expr: state.vector_gain
    - target: grad-field
      property: streamlineSeeds
      expr: Math.round(state.streamline_density)
    - target: grad-field
      property: resolution
      expr: Math.max(6, Math.min(18, Math.round(state.surface_resolution / 8)))

timeline:
  duration: 8
  loop: false
  speed: 1
  markers:
    - time: 0
      label: Init
      description: Start from the initial theta with high loss.
    - time: 7
      label: Converged
      description: Iterations approach a low-loss region near the minimum.
  tracks:
    - id: gd-steps
      type: step
      processId: gd
      steps:
        - { index: 0, time: 0.0, label: init }
        - { index: 1, time: 2.0, label: iter-1 }
        - { index: 2, time: 4.0, label: iter-2 }
        - { index: 3, time: 6.0, label: iter-3 }
        - { index: 4, time: 8.0, label: iter-4 }
    - id: gd-state
      type: state
      processId: gd
      states:
        - { time: 0.0, state: running }
        - { time: 8.0, state: completed }
    - id: gd-events
      type: event
      processId: gd
      events:
        - { time: 0.0, action: iterate, params: { step: 0 } }
    - id: point-x
      type: property
      target: point
      property: x
      keyframes:
        - { time: 0, value: 2.5 }
        - { time: 2, value: 1.572 }
        - { time: 4, value: 0.9904 }
        - { time: 6, value: 0.6251 }
        - { time: 8, value: 0.3951 }
    - id: point-z
      type: property
      target: point
      property: z
      keyframes:
        - { time: 0, value: -1.8 }
        - { time: 2, value: -1.18 }
        - { time: 4, value: -0.7708 }
        - { time: 6, value: -0.5021 }
        - { time: 8, value: -0.3263 }
    - id: trajectory-step
      type: property
      target: trajectory
      property: currentStep
      keyframes:
        - { time: 0, value: 0, easing: step }
        - { time: 2, value: 1, easing: step }
        - { time: 4, value: 2, easing: step }
        - { time: 6, value: 3, easing: step }
        - { time: 8, value: 4, easing: step }
    - id: loss
      type: property
      target: point
      property: loss
      keyframes:
        - { time: 0, value: 8.59 }
        - { time: 2, value: 3.49 }
        - { time: 4, value: 1.42 }
        - { time: 6, value: 0.58 }
        - { time: 8, value: 0.24 }
    - id: loss-label
      type: property
      target: loss-badge
      property: value
      keyframes:
        - { time: 0, value: "loss:8.59" }
        - { time: 2, value: "loss:3.49" }
        - { time: 4, value: "loss:1.42" }
        - { time: 6, value: "loss:0.58" }
        - { time: 8, value: "loss:0.24" }
